/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#13ecec',
          fixed: '#39fafa',
          container: '#004f4f',
          dark: '#0ebdbd',
        },
        secondary: {
          DEFAULT: '#4c9a9a',
          fixed: '#b2edec',
          container: '#1a2e2e',
        },
        tertiary: {
          DEFAULT: '#755b00',
          fixed: '#ffdf91',
          container: '#ffcf43',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        background: '#102222',
        surface: '#102222',
        'surface-dim': '#0c1a1a',
        'surface-bright': '#1a2e2e',
        'surface-container-lowest': '#081111',
        'surface-container-low': '#102222',
        'surface-container': '#1a2e2e',
        'surface-container-high': '#243a3a',
        'surface-container-highest': '#2e4646',
        'on-primary': '#002020',
        'on-primary-container': '#d0fbfb',
        'on-primary-fixed': '#002020',
        'on-primary-fixed-variant': '#004f4f',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#afeaea',
        'on-secondary-fixed': '#002020',
        'on-secondary-fixed-variant': '#0c4f4f',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#725800',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#594400',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-surface': '#f1fbfb',
        'on-surface-variant': '#d0fbfb',
        'on-background': '#f1fbfb',
        outline: '#4c9a9a',
        'outline-variant': '#3b4a49',
        'inverse-surface': '#f3fbfa',
        'inverse-on-surface': '#151d1d',
        'inverse-primary': '#006a6a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Space Grotesk"', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};