"""Initial migration

Revision ID: 2e2327dd7e22
Revises: 
Create Date: 2026-05-10 17:25:45.391602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2327dd7e22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('totalCredits', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('tx_hash', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('ipfs_cid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'ipfs_cid')
    op.drop_column('projects', 'tx_hash')
    op.drop_column('projects', 'createdAt')
    op.drop_column('projects', 'totalCredits')
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
